const state={themeIndex:0,page:1,pageSize:10,onlyFavorites:false};
const studied=new Set(JSON.parse(localStorage.getItem('cd-studied')||'[]'));
const favorites=new Set(JSON.parse(localStorage.getItem('cd-favorites')||'[]'));
const textCache=JSON.parse(localStorage.getItem('cd-text-cache')||'{}');
const $=s=>document.querySelector(s);
const chapterList=$('#chapterList'), cards=$('#verseCards');

function saveSets(){localStorage.setItem('cd-studied',JSON.stringify([...studied]));localStorage.setItem('cd-favorites',JSON.stringify([...favorites]));updateProgress();}
function updateProgress(){const total=THEMES.reduce((n,t)=>n+t.entries.length,0);$('#progressText').textContent=`${studied.size} de ${total} estudiados`;$('#progressBar').style.width=`${studied.size/total*100}%`; const t=THEMES[state.themeIndex]; $('#readCount').textContent=`${t.entries.filter(e=>studied.has(e.id)).length} estudiados`;}
function renderNav(filter=''){chapterList.innerHTML=''; THEMES.forEach((t,i)=>{if(filter&&!t.title.toLowerCase().includes(filter.toLowerCase()))return;const b=document.createElement('button');b.className='chapter-link'+(i===state.themeIndex?' active':'');b.innerHTML=`${i+1}. ${t.title}<small>300 versículos</small>`;b.onclick=()=>{state.themeIndex=i;state.page=1;state.onlyFavorites=false;renderAll();window.scrollTo({top:0,behavior:'smooth'});};chapterList.appendChild(b);});}
function filteredEntries(){let e=THEMES[state.themeIndex].entries;if(state.onlyFavorites)e=e.filter(x=>favorites.has(x.id));const q=$('#search').value.trim().toLowerCase();if(q)e=e.filter(x=>x.reference.toLowerCase().includes(q));return e;}
function renderAll(){const t=THEMES[state.themeIndex];$('#chapterNumber').textContent=`Capítulo ${state.themeIndex+1}`;$('#chapterTitle').textContent=t.title;$('#chapterIntro').textContent=t.intro;$('#verseCount').textContent=`${t.entries.length} versículos`;renderNav();renderCards();updateProgress();}
function renderCards(){const e=filteredEntries(),size=state.pageSize,pages=Math.max(1,Math.ceil(e.length/size));if(state.page>pages)state.page=pages;const slice=e.slice((state.page-1)*size,state.page*size);$('#pageInfo').textContent=`Página ${state.page} de ${pages}`;$('#prevBtn').disabled=state.page<=1;$('#nextBtn').disabled=state.page>=pages;cards.innerHTML=''; if(!slice.length){cards.innerHTML='<p>No hay resultados en esta selección.</p>';return;} slice.forEach(entry=>cards.appendChild(makeCard(entry)));}
function makeCard(e){const card=document.createElement('article');card.className='verse-card'+(studied.has(e.id)?' studied':'');card.innerHTML=`<div class="card-head"><div class="ref">${e.reference}</div><div class="card-tools"><button class="iconbtn fav">${favorites.has(e.id)?'★':'☆'}</button><button class="iconbtn speak">🔊</button><button class="iconbtn done">${studied.has(e.id)?'✓':'○'}</button></div></div><div class="verse-text" id="text-${e.id}"><span class="loading">Cargando texto RV1909…</span></div><div class="subtopic-pill">Subtema: ${e.subtopic}</div><div class="section-label">Interpretación específica con relación al tema</div><p>${e.interpretation}</p><div class="section-label">Aplicación práctica</div><p class="application">${e.application}</p>`;
 card.querySelector('.fav').onclick=()=>{favorites.has(e.id)?favorites.delete(e.id):favorites.add(e.id);saveSets();renderCards();};
 card.querySelector('.done').onclick=()=>{studied.has(e.id)?studied.delete(e.id):studied.add(e.id);saveSets();renderCards();};
 card.querySelector('.speak').onclick=()=>speakCard(e,card);
 loadVerseText(e,card.querySelector(`#text-${CSS.escape(e.id)}`));return card;}
async function loadVerseText(e,el){if(textCache[e.id]){el.textContent=textCache[e.id];return;} try{const url=`https://biblia-api.qhar.in/book/${e.book}/chapter/${e.chapter}/verse/${e.verse}`;const r=await fetch(url);if(!r.ok)throw 0;const d=await r.json();let text='';if(Array.isArray(d)) text=d.map(v=>v.text||v.content||v.verse||'').join(' '); else text=d.text||d.content||d.verse||d.value||'';if(typeof text==='object')text=JSON.stringify(text);if(!text) throw 0;text=String(text).replace(/<[^>]+>/g,'').trim();textCache[e.id]=text;localStorage.setItem('cd-text-cache',JSON.stringify(textCache));el.textContent=text;}catch{el.innerHTML=`<span class="loading">${e.reference} — texto bíblico no disponible sin conexión. La ficha puede seguir estudiándose y se intentará cargar de nuevo al conectarse.</span>`;}}
function speakCard(e,card){speechSynthesis.cancel();const text=card.querySelector('.verse-text').innerText+' '+e.interpretation+' '+e.application;const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';speechSynthesis.speak(u);}
$('#pageSize').onchange=e=>{state.pageSize=Number(e.target.value);state.page=1;renderCards();};$('#prevBtn').onclick=()=>{state.page--;renderCards();scrollTo(0,0)};$('#nextBtn').onclick=()=>{state.page++;renderCards();scrollTo(0,0)};
$('#search').oninput=e=>{state.page=1;renderNav(e.target.value);renderCards();};$('#favoritesBtn').onclick=()=>{state.onlyFavorites=!state.onlyFavorites;$('#favoritesBtn').textContent=state.onlyFavorites?'★ Mostrando favoritos':'★ Ver favoritos';state.page=1;renderCards();};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('cd-dark',document.body.classList.contains('dark')?'1':'0');};if(localStorage.getItem('cd-dark')==='1')document.body.classList.add('dark');
$('#printBtn').onclick=()=>window.print();$('#notesBtn').onclick=()=>{$('#globalNotes').value=localStorage.getItem('cd-notes')||'';$('#notesDialog').showModal();};$('#saveNotes').onclick=()=>localStorage.setItem('cd-notes',$('#globalNotes').value);
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden');}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');renderAll();
