const THEMES = [
 {id:'seguir',title:'Cómo seguir a Dios',intro:'Fe, obediencia, discipulado, carácter y perseverancia para orientar toda la vida hacia Dios.',subtopics:['Fe y confianza','Obediencia','Discipulado','Santidad','Perseverancia','Amor a Dios'],chapters:[['MAT',5],['MAT',6],['MAT',7],['JHN',14],['JHN',15],['JHN',16],['ROM',8],['ROM',12],['GAL',5],['EPH',4],['PHP',4],['COL',3],['JAS',1],['1PE',1],['1JN',4]]},
 {id:'milagros',title:'Los Milagros de Cristo',intro:'Obras y señales de Jesús que revelan su compasión, autoridad, identidad y llamado a la fe.',subtopics:['Sanidad','Autoridad sobre la naturaleza','Liberación','Provisión','Resurrección','Fe ante lo imposible'],chapters:[['MAT',8],['MAT',9],['MAT',14],['MAT',15],['MAT',17],['MRK',1],['MRK',2],['MRK',4],['MRK',5],['MRK',6],['LUK',5],['LUK',7],['LUK',8],['JHN',2],['JHN',11]]},
 {id:'promesas',title:'Promesas de Dios',intro:'Promesas bíblicas acerca de la presencia, fidelidad, dirección, provisión, perdón, consuelo, esperanza y salvación de Dios.',subtopics:['Presencia de Dios','Fidelidad','Dirección','Provisión','Consuelo','Esperanza y salvación'],chapters:[['GEN',12],['GEN',28],['EXO',14],['DEU',31],['JOS',1],['PSA',23],['PSA',34],['PSA',37],['PSA',91],['ISA',40],['ISA',41],['JER',29],['MAT',6],['JHN',14],['ROM',8]]},
 {id:'orar',title:'Cómo orar a Dios',intro:'Una guía bíblica para aprender adoración, confesión, gratitud, petición, intercesión, escucha y perseverancia en la oración.',subtopics:['Adoración','Confesión y arrepentimiento','Gratitud','Petición','Intercesión','Perseverancia'],chapters:[['1SA',1],['1KI',8],['PSA',5],['PSA',27],['PSA',51],['PSA',86],['PSA',103],['DAN',6],['DAN',9],['MAT',6],['MAT',7],['LUK',11],['LUK',18],['PHP',4],['JAS',5]]},
 {id:'matrimonio',title:'Cómo tener un buen matrimonio',intro:'Amor, pacto, respeto, comunicación, fidelidad, perdón y servicio mutuo para fortalecer la vida conyugal.',subtopics:['Pacto','Amor','Comunicación','Fidelidad','Perdón','Servicio mutuo'],chapters:[['GEN',2],['GEN',24],['PRO',5],['PRO',12],['PRO',15],['PRO',18],['PRO',31],['SNG',2],['SNG',4],['MAT',19],['1CO',7],['1CO',13],['EPH',5],['COL',3],['1PE',3]]},
 {id:'esposo',title:'Cómo ser un buen esposo',intro:'Amor sacrificial, liderazgo de servicio, fidelidad, responsabilidad, ternura y cuidado de la familia.',subtopics:['Amor sacrificial','Servicio','Fidelidad','Responsabilidad','Comunicación','Cuidado familiar'],chapters:[['GEN',2],['JOS',24],['PRO',4],['PRO',5],['PRO',20],['PRO',27],['MAT',5],['MAT',20],['1CO',13],['EPH',5],['COL',3],['1TI',3],['1TI',5],['1PE',3],['1JN',3]]},
 {id:'esposa',title:'Cómo ser una buena esposa',intro:'Sabiduría, dignidad, amor, colaboración, fortaleza, respeto, administración y vida espiritual.',subtopics:['Sabiduría','Dignidad','Colaboración','Fortaleza','Respeto','Vida espiritual'],chapters:[['RUT',1],['RUT',2],['1SA',1],['PRO',14],['PRO',19],['PRO',31],['SNG',4],['LUK',1],['LUK',10],['1CO',13],['EPH',5],['PHP',2],['COL',3],['1PE',3],['1JN',4]]},
 {id:'hijo',title:'Cómo ser un buen hijo',intro:'Honra, obediencia, gratitud, aprendizaje, responsabilidad, respeto a los padres y madurez.',subtopics:['Honra','Obediencia','Gratitud','Aprendizaje','Responsabilidad','Madurez'],chapters:[['EXO',20],['DEU',6],['1SA',3],['PRO',1],['PRO',3],['PRO',4],['PRO',6],['PRO',10],['PRO',13],['PRO',15],['PRO',20],['PRO',23],['LUK',2],['EPH',6],['COL',3]]},
 {id:'comunidad',title:'Cómo convivir en comunidad',intro:'Justicia, misericordia, cooperación, servicio, reconciliación, solidaridad y construcción de paz.',subtopics:['Justicia','Misericordia','Cooperación','Servicio','Reconciliación','Paz'],chapters:[['LEV',19],['DEU',15],['PRO',11],['PRO',14],['PRO',17],['MAT',5],['MAT',18],['LUK',10],['ACT',2],['ACT',4],['ROM',12],['1CO',12],['GAL',6],['EPH',4],['JAS',2]]},
 {id:'administrador',title:'Cómo ser un buen administrador',intro:'Mayordomía, planeación, prudencia, integridad, rendición de cuentas, liderazgo y uso sabio de recursos.',subtopics:['Mayordomía','Planeación','Integridad','Recursos','Liderazgo','Rendición de cuentas'],chapters:[['GEN',41],['EXO',18],['1KI',3],['NEH',2],['NEH',4],['PRO',6],['PRO',10],['PRO',11],['PRO',21],['PRO',22],['PRO',27],['MAT',25],['LUK',14],['LUK',16],['1CO',4]]},
 {id:'trabajador',title:'Cómo ser un buen trabajador',intro:'Diligencia, excelencia, honestidad, disciplina, cooperación, servicio y responsabilidad laboral.',subtopics:['Diligencia','Excelencia','Honestidad','Disciplina','Cooperación','Responsabilidad'],chapters:[['GEN',39],['EXO',35],['RUT',2],['NEH',4],['PRO',6],['PRO',10],['PRO',12],['PRO',13],['PRO',14],['PRO',22],['PRO',24],['ECC',3],['COL',3],['1TH',4],['2TH',3]]},
 {id:'ventas',title:'Cómo poder mercadear y vender',intro:'Principios bíblicos aplicables a ventas éticas: escuchar, servir, comunicar con verdad, crear valor, negociar justamente y construir confianza.',subtopics:['Escuchar necesidades','Verdad comercial','Valor y servicio','Negociación justa','Confianza','Seguimiento'],chapters:[['GEN',23],['GEN',41],['RUT',2],['PRO',10],['PRO',11],['PRO',16],['PRO',18],['PRO',20],['PRO',22],['PRO',25],['PRO',27],['MAT',7],['LUK',16],['ACT',18],['2CO',8]]}
];

const BOOK_NAMES={GEN:'Génesis',EXO:'Éxodo',LEV:'Levítico',NUM:'Números',DEU:'Deuteronomio',JOS:'Josué',JDG:'Jueces',RUT:'Rut','1SA':'1 Samuel','2SA':'2 Samuel','1KI':'1 Reyes','2KI':'2 Reyes','1CH':'1 Crónicas','2CH':'2 Crónicas',EZR:'Esdras',NEH:'Nehemías',EST:'Ester',JOB:'Job',PSA:'Salmos',PRO:'Proverbios',ECC:'Eclesiastés',SNG:'Cantares',ISA:'Isaías',JER:'Jeremías',LAM:'Lamentaciones',EZK:'Ezequiel',DAN:'Daniel',HOS:'Oseas',JOL:'Joel',AMO:'Amós',OBA:'Abdías',JON:'Jonás',MIC:'Miqueas',NAM:'Nahúm',HAB:'Habacuc',ZEP:'Sofonías',HAG:'Hageo',ZEC:'Zacarías',MAL:'Malaquías',MAT:'Mateo',MRK:'Marcos',LUK:'Lucas',JHN:'Juan',ACT:'Hechos',ROM:'Romanos','1CO':'1 Corintios','2CO':'2 Corintios',GAL:'Gálatas',EPH:'Efesios',PHP:'Filipenses',COL:'Colosenses','1TH':'1 Tesalonicenses','2TH':'2 Tesalonicenses','1TI':'1 Timoteo','2TI':'2 Timoteo',TIT:'Tito',PHM:'Filemón',HEB:'Hebreos',JAS:'Santiago','1PE':'1 Pedro','2PE':'2 Pedro','1JN':'1 Juan','2JN':'2 Juan','3JN':'3 Juan',JUD:'Judas',REV:'Apocalipsis'};

const THEME_GUIDES={
 seguir:{principles:['confiar en Dios por encima del temor','convertir la fe en obediencia cotidiana','permanecer cerca de Cristo','formar un carácter coherente con el evangelio','perseverar aun en dificultad','amar a Dios con toda la vida'],actions:['tomar una decisión de obediencia concreta','examinar qué hábito necesita cambiar','reservar un tiempo de lectura y oración','practicar hoy una virtud cristiana','mantener fidelidad en una dificultad','servir a otra persona como expresión de amor a Dios']},
 milagros:{principles:['reconocer la compasión de Jesús ante el sufrimiento','contemplar la autoridad de Cristo','responder con fe sin convertir a Dios en una fórmula','ver la señal como revelación de quién es Jesús','reconocer la provisión de Cristo','entender que el poder de Jesús conduce a confianza y transformación'],actions:['identificar qué revela el relato acerca de Jesús','presentar a Dios una necesidad concreta en oración','leer el relato completo y observar la respuesta de las personas','anotar qué cambia en tu visión de Cristo','agradecer por una obra de Dios ya recibida','acompañar con compasión a alguien que atraviesa necesidad']},
 promesas:{principles:['descansar en la presencia de Dios','confiar en la fidelidad de Dios aun cuando el cumplimiento tarde','buscar dirección sin abandonar la responsabilidad personal','recibir la provisión de Dios con gratitud y buena mayordomía','hallar consuelo en el carácter de Dios','sostener esperanza en la salvación y el futuro que Dios promete'],actions:['escribir la promesa y el atributo de Dios que la sostiene','orar la promesa sin sacarla de su contexto','recordar una ocasión en que Dios mostró fidelidad','distinguir entre una promesa bíblica y un deseo personal','compartir una palabra de esperanza con alguien','actuar hoy de manera coherente con la confianza que profesas']},
 orar:{principles:['comenzar reconociendo quién es Dios','acercarse con sinceridad, confesión y arrepentimiento','cultivar gratitud antes de concentrarse en las necesidades','presentar peticiones con confianza y humildad','interceder por otras personas','perseverar en oración sin manipular a Dios'],actions:['orar cinco minutos centrado sólo en adoración','confesar con sinceridad algo que necesita corrección','anotar tres motivos concretos de gratitud','presentar una petición y dejar el resultado en manos de Dios','orar hoy por una persona específica','establecer un horario breve y constante de oración']},
 matrimonio:{principles:['proteger el pacto matrimonial','expresar amor mediante acciones concretas','comunicarse con verdad y respeto','cultivar fidelidad emocional y física','practicar perdón y reparación','servirse mutuamente sin competir por poder'],actions:['tener una conversación de veinte minutos sin interrupciones','hacer una acción de servicio por el cónyuge','expresar una necesidad con claridad y respeto','reconocer una cualidad concreta del cónyuge','pedir perdón por una conducta específica','acordar una mejora pequeña para esta semana']},
 esposo:{principles:['amar de manera sacrificial','liderar sirviendo y no dominando','mantener fidelidad de pensamiento, palabra y conducta','asumir responsabilidades familiares','escuchar y comunicarse con ternura','cuidar el bienestar integral de la esposa y la familia'],actions:['preguntar a tu esposa qué necesita de ti esta semana','cumplir una responsabilidad familiar pendiente','reconocer una fortaleza de tu esposa','escuchar sin interrumpir ni defenderte','pedir perdón si has causado daño','planificar tiempo de calidad en familia']},
 esposa:{principles:['actuar con sabiduría','preservar la dignidad propia y ajena','colaborar desde el respeto mutuo','usar la fortaleza para edificar','comunicar respeto sin renunciar a la verdad','cultivar una vida espiritual sólida'],actions:['identificar una acción que mejore la colaboración','expresar una necesidad con claridad','reconocer una fortaleza de tu esposo','organizar una responsabilidad del hogar con criterio','reservar tiempo para oración y reflexión','abordar un desacuerdo con respeto y límites sanos']},
 hijo:{principles:['honrar a padres y cuidadores','obedecer lo bueno con actitud responsable','cultivar gratitud','aprender de la corrección y la experiencia','cumplir deberes sin depender siempre de recordatorios','crecer en madurez y criterio'],actions:['hacer hoy un gesto concreto de gratitud','cumplir una responsabilidad sin que te la recuerden','escuchar una corrección antes de responder','pedir consejo sobre una decisión','reparar una falta mediante una acción concreta','expresar un desacuerdo con respeto']},
 comunidad:{principles:['practicar justicia en el trato','mostrar misericordia','cooperar para el bien común','servir especialmente al vulnerable','buscar reconciliación sin negar la verdad','construir paz mediante responsabilidad y respeto'],actions:['realizar una acción de servicio comunitario','escuchar a alguien con quien discrepas','ayudar a una persona vulnerable','proponer una colaboración sencilla','resolver un conflicto separando hechos de suposiciones','cumplir un compromiso adquirido con otros']},
 administrador:{principles:['entender los recursos como una mayordomía','planificar antes de comprometer recursos','actuar con integridad aun cuando nadie supervise','evitar desperdicio y usar bien tiempo y dinero','liderar distribuyendo responsabilidades con criterio','rendir cuentas con transparencia'],actions:['detectar hoy un desperdicio evitable','escribir objetivo, costo, beneficio y riesgo antes de decidir','revisar un presupuesto o inventario','delegar una tarea con responsable y fecha','definir un indicador sencillo de control','documentar una decisión importante']},
 trabajador:{principles:['trabajar con diligencia','buscar excelencia sin perfeccionismo paralizante','ser honesto en tiempo, dinero e información','mantener disciplina aun sin supervisión','cooperar y respetar a compañeros','asumir responsabilidad por resultados y errores'],actions:['terminar primero la tarea más importante','revisar la calidad antes de entregar','corregir un error sin ocultarlo','mejorar puntualidad u orden','ayudar a un compañero en una necesidad concreta','documentar una mejora de proceso']},
 ventas:{principles:['escuchar antes de ofrecer','comunicar con verdad y sin exagerar','crear valor real para el cliente','negociar con justicia','construir confianza mediante promesas cumplidas','dar seguimiento pensando en la relación y no sólo en la transacción'],actions:['hacer tres preguntas antes de presentar el producto','revisar que una promesa comercial sea verificable','explicar claramente precio, condiciones y limitaciones','buscar una solución donde ambas partes reciban valor','dar seguimiento a un cliente anterior','eliminar de tu discurso una frase que pueda inducir a engaño']}
};

function chapterEmphasis(theme, book, chapter, ci){
 const s=theme.subtopics;
 return s[(ci + chapter) % s.length];
}
function specificInterpretation(theme, entry, ci, vi){
 const g=THEME_GUIDES[theme.id];
 const principle=g.principles[(ci+vi)%g.principles.length];
 const emphasis=chapterEmphasis(theme,entry.book,entry.chapter,ci);
 const variants=[
  `En ${entry.reference}, leído dentro del tema «${theme.title}», el énfasis de estudio es ${emphasis.toLowerCase()}. Este pasaje orienta a ${principle}. La idea central no debe aislarse de su contexto bíblico: se usa aquí como una ventana para examinar cómo ese principio puede formar decisiones, carácter y relaciones.`,
  `${entry.reference} se incorpora a este capítulo por su relación con ${emphasis.toLowerCase()}. Aplicado al tema «${theme.title}», invita a ${principle}. La enseñanza no consiste sólo en conocer una frase bíblica, sino en reconocer el principio que comunica y contrastar con él la conducta cotidiana.`,
  `Al estudiar ${entry.reference} desde la perspectiva de ${emphasis.toLowerCase()}, este versículo ayuda a profundizar «${theme.title}» mediante un principio concreto: ${principle}. Su interpretación temática busca conectar el mensaje bíblico con una respuesta responsable, evitando usar el texto como una fórmula automática o fuera de contexto.`,
  `Dentro de «${theme.title}», ${entry.reference} funciona como una reflexión sobre ${emphasis.toLowerCase()}. El principio que se destaca es ${principle}. Por eso, el valor del versículo está en permitir que la verdad bíblica examine motivos, prioridades y acciones, y no únicamente en memorizar su referencia.`
 ];
 return variants[(ci*20+vi)%variants.length];
}
function specificApplication(theme, entry, ci, vi){
 const g=THEME_GUIDES[theme.id];
 const action=g.actions[(ci*2+vi)%g.actions.length];
 const sub=chapterEmphasis(theme,entry.book,entry.chapter,ci);
 const variants=[
  `Aplicación: ${action}. Después, escribe una frase indicando cómo ${entry.reference} ilumina el subtema «${sub}» en tu situación actual.`,
  `Práctica de hoy: ${action}. Al terminar, vuelve a ${entry.reference} y anota qué decisión concreta puedes mantener durante los próximos siete días.`,
  `Ejercicio: ${action}. Evalúa luego si tu manera de actuar refleja realmente el principio trabajado en «${sub}» y registra una mejora específica.`,
  `Acción sugerida: ${action}. Convierte la reflexión de ${entry.reference} en un compromiso pequeño, observable y realista para hoy.`
 ];
 return variants[(ci+vi)%variants.length];
}

function buildEntries(theme){
 const arr=[];
 theme.chapters.forEach(([book,chapter],ci)=>{
   for(let verse=1; verse<=20; verse++){
     const vi=verse-1;
     const entry={id:`${theme.id}-${book}-${chapter}-${verse}`,book,chapter,verse,reference:`${BOOK_NAMES[book]} ${chapter}:${verse}`};
     entry.subtopic=chapterEmphasis(theme,book,chapter,ci);
     entry.interpretation=specificInterpretation(theme,entry,ci,vi);
     entry.application=specificApplication(theme,entry,ci,vi);
     arr.push(entry);
   }
 });
 return arr;
}
THEMES.forEach(t=>t.entries=buildEntries(t));
